# Generated by Django 5.2.5 on 2025-08-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('campus', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, help_text='% mensual, fijo', max_digits=5)),
                ('comision', models.DecimalField(decimal_places=2, help_text='% total sobre monto', max_digits=5)),
                ('plazo', models.PositiveIntegerField(help_text='Número de cuotas/meses')),
                ('fecha_inicio', models.DateField(help_text='Primera fecha de pago (15 o fin de mes)')),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('cheque', models.CharField(blank=True, default='', max_length=30)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=12)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='prestamos.prestamo')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('prestamo', 'numero')},
            },
        ),
    ]
