# Generated by Django 5.2.5 on 2025-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Reprogramado', 'Reprogramado')], default='Pendiente', max_length=12),
        ),
    ]
