# Generated by Django 5.2.5 on 2026-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_cuota_observacion_alter_cuota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
