# Generated by Django 5.2.4 on 2025-07-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Titulo',
            new_name='title',
        ),
    ]
