# Generated by Django 5.2.4 on 2025-07-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_instructor_task_fecha_fin_task_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
