# Generated by Django 5.2.4 on 2025-07-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_instructor_delete_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
